{
 "title": "Air",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awairlocal_humid", "legendFormat": "humidity" },
    { "expr": "awairlocal_abs_humid", "legendFormat": "absolute humidity" },
    { "expr": "awairlocal_dew_point", "legendFormat": "dew point" }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awairlocal_co2_est", "legendFormat": "CO2" },
    { "expr": "awairlocal_co2", "legendFormat": "estimated CO2 " }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awairlocal_temp" }
   ]
  },
  {
   "title": "PM2.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awairlocal_pm10_est", "legendFormat": "estimated PM10 " },
    { "expr": "awairlocal_pm25", "legendFormat": "PM2.5" }
   ]
  },
  {
   "title": "VOC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awairlocal_voc", "legendFormat": "VOC" },
    { "expr": "awairlocal_voc_baseline", "legendFormat": "VOC baseline" }
   ]
  },
  {
   "title": "Ethanol",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awairlocal_voc_ethanol_raw", "legendFormat": "Ethanol (raw)" }
   ]
  }
 ]
}
{
 "title": "Awair Scraper",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GetAirData calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(awairlocal_ops_GetAirData_calls[1m])"
    }
   ]
  }
 ]
}